import Providers from "../components/Providers";  // 경로 주의!
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


/* 📐 폰트 설정 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* 🏷️ 메타데이터 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* 🌐 루트 레이아웃 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  <Providers>
    {children}
  </Providers>
</body>
    </html>
  );
}
